name: Build and publish AZP Agent Debian Stretch-Slim image
 
on:
  push:
    paths:
    - 'dockerfiles/debian-stretch-slim/**'
    - '!dockerfiles/debian-stretch-slim/README.md'  

env:
  _GH_BASE_URI: https://github.com/
  _CALVER_VERSION: 20200313.1
  _BASE_IMAGE_VERSION: stretch-slim
  _BASE_IMAGE: debian
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish to Docker Repository
        env:
          _IMAGE_LONG_VERSION: ${{ env._BASE_IMAGE }}-${{ env._BASE_IMAGE_VERSION }}-${{ env._CALVER_VERSION }}
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          context: dockerfiles/debian-stretch-slim
          buildargs: BASE_IMAGE_VERSION=${{ env._BASE_IMAGE_VERSION }}, VCS_URL=${{ env._GH_BASE_URI }}${{ env.GITHUB_REPOSITORY }}, VCS_REF=${{ env.GITHUB_SHA }}, IMAGE_LONG_VERSION=${{ env._IMAGE_LONG_VERSION }}
          name: ${{ secrets.DOCKERHUB_REPO }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
          tags: ${{ env._BASE_IMAGE }}-${{ env._BASE_IMAGE_VERSION }}-${{ env._CALVER_VERSION }}, ${{ env._BASE_IMAGE }}-${{ env._BASE_IMAGE_VERSION }}